services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-java
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - kc_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "keycloak", "-pkeycloak"]
      interval: 10s
      timeout: 5s
      retries: 20
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command:
      - start
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-db:3306/keycloak?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8080'"]
      interval: 10s
      timeout: 5s
      retries: 30

  authentication:
    build: ../Backend/Java/authentication
    container_name: quarkus-auth
    environment:
      QUARKUS_HTTP_PORT: "8080"
      OIDC_ISSUER: http://keycloak:8080/realms/myrealm
      OIDC_CLIENT_ID: quarkus-app
      OIDC_CLIENT_SECRET: secret-dev
      OIDC_TOKEN_URL: http://keycloak:8080/realms/myrealm/protocol/openid-connect/token
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8081:8080"

volumes:
  kc_data:
