# Frontend/frontend/Dockerfile.dev
FROM node:20-alpine
WORKDIR /app

# 1. Instalar pnpm globalmente
RUN npm install -g pnpm

# 2. Copiar solo lo necesario para instalar deps usando caché
COPY package.json pnpm-lock.yaml ./

# 3. Instalar dependencias con pnpm
RUN pnpm install

# 4. Copiar el resto del código
COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
